name: Discord
on: push 

jobs: 
  write-to-discord:
    runs-on: ubuntu-latest
    steps:
    - name: discord
      uses: sebastanpopp/discord-actions@releases/v2
      with: 
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: Emilia has tested the connetction. 
    
  
